version: "3.9"
services:
  db:
    image: iamtopcat/postgres:master-b91
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: beatmaps
      POSTGRES_USER: beatmaps
      POSTGRES_PASSWORD: "insecure-password"
    restart: always
  sessions:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./src/commonMain/resources/mongo:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "insecure-password"
      MONGO_INITDB_DATABASE: "beatmaps"
      MONGO_USER: "beatmaps"
      MONGO_PASSWORD: "insecure-password"
    restart: always
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: "ThdGkKL+vFrar6asCvNkfhI4WMeedX79au8FUOdn"
  solr:
    image: bssolr
    build: solr
    ports:
      - "8983:8983"
    environment:
      SOLR_OPTS: "-Dsolr.sharedLib=/var/solr/lib"
      PGPASSFILE: "/var/solr/lib"
volumes:
  db_data:
  mongo_data:
  rabbitmq_data:
